services:
    php:
        build:
            context: ./
            dockerfile: docker/apache/Dockerfile
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf

    mariadb:
        image: mariadb:latest
        hostname: ${DB_HOST}
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf:ro

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mariadb
        links:
            - mariadb
        ports:
            - "8181:80"
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}